### ISSUE TITLE
Not able to make stackline work for yabai

### ISSUE THREAD

**Issue by tonyma** [AdamWagner/stackline#107]
Not able to make the stack icon works for yabai, here are the hammerspoon console log when triggering window stack in yabai:

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/4219509/170865138-343561aa-08a4-4681-a4da-0932a1db30ca.png">

And getting this error when run `hs -c "stackline.config:toggle('appearance.showIcons')"` command
<img width="823" alt="image" src="https://user-images.githubusercontent.com/4219509/170865588-20885e31-65c8-47bb-9a67-09dd5ed36f02.png">

I am using M1 Mac Pro

Anyone able to help, please 🙏🏼

**Comment by Mr-istov** [comment]
Hey @tonyma, the first warning looks like it might be related to https://github.com/AdamWagner/stackline/issues/82.
I had the same problem on an M1 Mac, and since I installed `yabai` through `brew`, it's path is under `/opt/homebrew/bin/yabai`, so after tweaking the `conf.lua` as they mentioned in that issue, it started working.

**Comment by tonyma** [comment]
Awesome, it just worked. thanks @Mr-istov .
