### ISSUE TITLE
Indicator not shown when stack width < minimum width of stacked window. [Original: Iterm icon is not visible]

### ISSUE THREAD

**Issue by Coobaha** [AdamWagner/stackline#32]
Hi @AdamWagner 

First of all thanks for writing this scripts :) nice addition to yabai 💯 

Grouping by stackId is buggy. Assumption to make stackId based on x+y+w+h is incorrect, as some windows can have different dimensions (for instance terminal or iterm and any other app that have weird behaviour when very narrow).

https://github.com/AdamWagner/stackline/blob/4791ca17a427c117de6d45ee5eaf10660a71e9b4/stackline/window.lua#L337

Replacing 
https://github.com/AdamWagner/stackline/blob/4791ca17a427c117de6d45ee5eaf10660a71e9b4/stackline/query.lua#L34

with 
```lua
byStack = u.groupBy(windows, 'stackId')
```

Solves it, but not sure if this is a correct fix. At least it works for me :) Could make a PR if this is the right way to fix it

Before
![image](https://user-images.githubusercontent.com/2446638/91634305-18798600-e9f8-11ea-91c9-8dfe43afa428.png)

After:
![image](https://user-images.githubusercontent.com/2446638/91634299-0e578780-e9f8-11ea-9564-cf1aed1ad20f.png)

**UPD**: Nah naive fix makes it more buggy :/

**Comment by AdamWagner** [comment]
@Coobaha Thanks for the issue.

>Grouping by stackId is buggy. Assumption to make stackId based on x+y+w+h is incorrect, as some windows can have different dimensions (for instance terminal or iterm and any other app that have weird behaviour when very narrow).

You're absolutely right that grouping by stackId (which is really just a string representation of the window frame) is not always reliable, and it's good to call it out here so that others know. 

My personal, interim solution for this is to _not make stacks that are very narrow_. The minimum window size in macOS is generally an annoyance, and that continues to e true here.

---

>UPD: Nah naive fix makes it more buggy :/

Yep :-) We'll want to continue filtering out stacks that only contain 1 window. 

---

I do have an idea for how we can improve this, though:

**Fuzz the `stackId`**. It would be relatively simple to just round window dimensions to the nearest number divisible by 5 (or 10), right before stringifying the window frame into the stackId. This would probably fix the issue, and be unlikely to produce false positives. It would still fail with _really_ skinny stacks that are more than `fuzzFactor` less than one of the windows' minimum size, but I'm inclined to just call this out as an unsupported case.

What do you think about ↑ ?

**Comment by Coobaha** [comment]
@AdamWagner yea this probably should fix it, great idea!
