### ISSUE TITLE
JSON decoding error preventing Stackline from working...

### ISSUE THREAD

**Issue by RauschUndNot** [AdamWagner/stackline#39]
Hello,

I just installed Stackline. I also have `jq` and `yabai` installed. I am receiving this error: 

> `2020-09-09 17:06:39: 17:06:39 ERROR:   LuaSkin: hs.task callback: ...rs/myUserName/.hammerspoon/stackline/stackline/query.lua:11: The data couldn‚Äôt be read because it isn‚Äôt in the correct format.
> stack traceback:
> 	[C]: in function 'hs.json.decode'
> 	...rs/myUserName/.hammerspoon/stackline/stackline/query.lua:11: in function <...rs/myUserName/.hammerspoon/stackline/stackline/query.lua:10>`

Stackline is not working. Thank you!

Late 2011, 13-inch MacBook Pro
MacOS High Sierra

Edit: removed username...

**Comment by RauschUndNot** [comment]
Hello again,

I closed all windows, waited for the clock to reach the next minute, then reloaded the Hammerspoon config. I still got the same message. Here is the complete log from when I reloaded:

> `2020-09-10 23:26:08: ========================================
> 2020-09-10 23:26:08: STARTING STACKLINE	==========
> 2020-09-10 23:26:08: ========================================
> 2020-09-10 23:26:08: -- Loading extension: task
> 2020-09-10 23:26:08: -- Loading extension: json
> 2020-09-10 23:26:08: ********
> 2020-09-10 23:26:08: 23:26:08 ERROR:   LuaSkin: hs.task callback: ...rs/myUserName/.hammerspoon/stackline/stackline/query.lua:11: The data couldn‚Äôt be read because it isn‚Äôt in the correct format.
> stack traceback:
> 	[C]: in function 'hs.json.decode'
> 	...rs/myUserName/.hammerspoon/stackline/stackline/query.lua:11: in function <...rs/myUserName/.hammerspoon/stackline/stackline/query.lua:10>
> 2020-09-10 23:26:08: ********
> 2020-09-10 23:26:13: 23:26:13 ** Warning:   wfilter: Hammerspoon (981) is not registered yet
> 2020-09-10 23:26:13: 23:26:13 ** Warning:   wfilter: No accessibility access to app AvidAppManHelper (no watcher pid)
> `

**Comment by AdamWagner** [comment]
Thanks!

I don't see anything unusual in the reload log. That is – it',s very similar to my own logs in the rare case I've encountered the `The data couldn‚Äôt be read because it isn‚Äôt in the correct format.` problem.

AFAIK, `** Warning: wfilter: No accessibility access to app AvidAppManHelper (no watcher pid)` is normal & nothing to worry about.  It's also not related to `stackline` (simply loading `hs.window.filter` will spit out lines like this). 

The only json that is decoded comes from the `yabai` shell script that is called to get stack indexes. I can confirm that this script does _not_ return window titles anymore… just the window ID and stack index… both of which should be easy-to-decode integers. 

Further corroboration: the error occurs at `query.lua:11`, which _is_ where the aforementioned shell script is called. 

Could you try the following test?

1. Make sure `yabai` is running (hammerspoon doesn't need to be running)
2. `cd` to `~/.hammerspoon`
3.. Run the stackline shell script from your terminal: `./stackline/bin/yabai-get-stack-idx`


The output _should_ look like this:

```
{"360539":0,"359670":2,"359558":1,"359608":2,"359619":3,"359624":4,"359663":1,"361528":0,"361527":0,"357711":1,"361376":2,"359352":0}
```

If you can observe substantially different output or an error… then we're getting pretty close!


---

**A shot in the dark**

`jq` is a dependency of `stackline`, and is invoked with its absolute path when installed via `brew install jq`:  `/usr/local/bin/jq`

Can you confirm that you have `jq` installed, and that its location is `/usr/local/bin/jq`? 

You can review dependencies here: https://github.com/AdamWagner/stackline/wiki/Install-dependencies

**Comment by AdamWagner** [comment]
@RauschUndNot I just add a guard + retry for json decoding: https://github.com/AdamWagner/stackline/commit/ced44734397bae69aa89c410f274106042024fc0

**Comment by RauschUndNot** [comment]
Hello,

It turns out that `jq` was installed in my home directory. I set up a link to `jq` inside of `/usr/bin/local` and that fixed it. Thank you!


Andrew

**Comment by AdamWagner** [comment]
Awesome! Glad to hear it @RauschUndNot
