### ISSUE TITLE
Support for multiple stacks per monitor?

### ISSUE THREAD

**Issue by alextremblay** [AdamWagner/stackline#43]
Hello,

First off, thank you for making this. it's really slick!

I've started using yabai's stacking feature and stackline recently, and I think it's great, but I've noticed a problem. If i have two stacks in a given space, the second stack has no stackline

The GIF in your project's readme makes it look like multiple stacks in a given space should work and each have their own stacklines, but i can't find anything in the documentation about it

Is this a bug, or a feature request?

**Comment by alextremblay** [comment]
Ok, so it seems this may have been a red herring. I am now able to see a stackline for the second stack on my main display

The only difference between now and when I opened this issue is that previously, my second stack ocnsisted of one hammerspoon console window and two alacritty terminal windows.

Now my second stack consists of one hammerspoon console window and one vscode window and I am able to see its stackline

I suspect this may be related to #44 
maybe if only one icon is visible stackline simply doesn't render a stackline?

**Comment by AdamWagner** [comment]
>I've started using yabai's stacking feature and stackline recently, and I think it's great, but I've noticed a problem. If i have two stacks in a given space, the second stack has no stackline

Yikes! That would definitely be a bug. 

>The only difference between now and when I opened this issue is that previously, my second stack ocnsisted of one hammerspoon console window and two alacritty terminal windows. […] I suspect this may be related to #44

Yep, this is almost certainly the same root issue discussed in #44. 

>maybe if only one icon is visible stackline simply doesn't render a stackline?

Window indicators are driven by `stackline` state – so either a stacked window has been properly detected and renders as expected, _or_ it's not meeting the criteria necessary to be considered part of the stack and doesn't render at all. That is to say: icon visibility can not influence other behaviors. For example, if a window's icon could not be fetched due to, say, a macOS bug, that would have no effect on the way `stackline` renders the stack overall. 

Let me know if you run into any trouble verifying that the root issue is what we think it is.

**Comment by alextremblay** [comment]
Hi, sorry for not getting back to you. 

I haven't experienced the issue since then. I see you put out a new version with adjustable fuzz factor. Thanks for that!

If i run into the issue again, I'll try tweaking that.
